name: Daily Notion Graph Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-notion-graph:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: |
        cd notion-graph-generator
        npm install
      
    - name: Run Notion Graph script
      run: |
        cd notion-graph-generator
        node index.js
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        
    - name: Upload JSON as artifact
      uses: actions/upload-artifact@v3
      with:
        name: notion-graph
        path: notion-graph-generator/notion-graph.json
        
    - name: Commit and push if changed
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add notion-graph-generator/notion-graph.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Notion graph JSON" && git push)
